[project]
name = "home-work-azl"
version = "0.1.0"
description = "Science News Reader"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "psycopg2-binary>=2.9.9",
    "python-dateutil>=2.9.0.post0",
    "requests>=2.32.3",
    "sqlalchemy>=2.0.35",
]
