apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          env:
              {{- range .Values.api.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
              {{- end }}
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: 5000
      targetPort: 5000
      name: tcp
      protocol: TCP
  selector:
    app: api
