apiVersion: v2
name: infrastructure
description: A Helm chart for Azul PoC

type: application

version: 0.1.2

appVersion: "0.1.0"

dependencies:
  - name: postgresql
    version: "16"
    repository: "https://charts.bitnami.com/bitnami"
