postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 16
    pullPolicy: IfNotPresent
  primary:
    persistence:
      enabled: true
      size: 8Gi
    service:
      type: LoadBalancer
      port: 5432
  auth:
    username: postgres
    password: mypassword  # Replace with a secure password
    database: poc

cronjob:
  enabled: true
  schedule: "0 * * * *"  # Every hour
  image:
    repository: poc
    tag: latest
    pullPolicy: Never # to support local image, for PROD -> IfNotPresent
  name: processor-cronjob
  env:
    - name: DB_HOST
      value: "poc-postgresql"

kong:
  ingressController:
    enabled: true
  proxy:
    http:
      enabled: true
      servicePort: 8080
  env:
    database: "off"

api:
  image:
    repository: api
    tag: latest
    pullPolicy: Never # to support local image, for PROD -> IfNotPresent
  service:
    type: ClusterIP
    port: 5000
  env:
    - name: DB_HOST
      value: "poc-postgresql"
  ingress:
    enabled: true
    annotations:
      konghq.com/strip-path: "false"
    hosts:
      - paths:
          - path: /health
            pathType: ImplementationSpecific
          - path: /news
            pathType: ImplementationSpecific
