[project]
name = "src"
version = "0.1.0"
description = "Science News Reader"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dateutil>=2.9.0.post0",
    "requests>=2.32.3",
]
